In [1]:
import gc
import os
import random
import time
import warnings
import sys
warnings.simplefilter("ignore")
import os
#import pdb
#import zipfile
#import pydicom
from albumentations import *
from albumentations.pytorch import ToTensor
import cv2
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import segmentation_models_pytorch as smp
from sklearn.model_selection import KFold
import tifffile as tiff
import torch
import torch.backends.cudnn as cudnn
import torch.nn as nn
from torch.nn import functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.utils.data import DataLoader, Dataset, sampler
from tqdm import tqdm_notebook as tqdm
import segmentation_models_pytorch
import matplotlib.pyplot as plt
torch.backends.cudnn.benchmark=True
from datetime import datetime
sys.path.append("/home/mlrig/Documents/TFG/Code")
from utils_pipeline import *

In [2]:
dir_name  = "/media/mlrig/ssh/TFG/"+str(datetime.now())
os.mkdir(dir_name)

In [3]:
def set_seed(seed=2**3):
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
set_seed(121)

In [4]:
fold = 0
nfolds = 5
reduce = 4
sz = 256

BATCH_SIZE = 2
DEVICE = ('cuda' if torch.cuda.is_available() else 'cpu')
NUM_WORKERS = 1
SEED = 2020
TH = 0.39  #threshold for positive predictions

DATA = '/home/mlrig/Documents/kaggle/Hubmap/test/'
LABELS = '/home/mlrig/Documents/kaggle/Hubmap/train.csv'
MASKS = '/home/mlrig/Documents/TFG/carla-simulator/out_seg_city/'
TRAIN = '/home/mlrig/Documents/TFG/carla-simulator/rgb/'

In [5]:
df = pd.DataFrame(os.listdir(TRAIN),columns=["id"])
images = []
for file in os.listdir("/home/mlrig/Documents/kaggle/Hubmap/train"):
    if file.endswith(".tiff"):
            images.append(file.split(".")[0])

In [6]:
 def get_aug(p=1.0):
    return Compose([
        Resize(600,800)

    ])

In [7]:
classes = [142,162,-1]
classes_dict = {}
classes_dict[142] = 0
classes_dict[162] = 1
ds_t = HuBMAPDataset(df["id"],classes,classes_dict,get_aug(),TRAIN,MASKS,True)
dataloader_t = torch.utils.data.DataLoader(ds_t,batch_size=1, shuffle=True,num_workers=NUM_WORKERS)


In [8]:
for i, data in enumerate(dataloader_t):
    image,labels,file_name = data    
    cv2.imwrite(dir_name+file_name[0],labels.numpy().reshape(600,800,3))

(600, 800)
tensor([0, 2]) {142: 0, 162: 1}


TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mlrig/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mlrig/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mlrig/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mlrig/Documents/TFG/Code/utils_pipeline.py", line 71, in __getitem__
    mask_onehot  = torch.nn.functional.one_hot(torch.tensor(mask).long().squeeze(0),num_classes=len(self.classes))
TypeError: can't convert np.ndarray of type numpy.uint64. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.


(600, 800)
tensor([0, 2]) {142: 0, 162: 1}
(600, 800)
tensor([0, 2]) {142: 0, 162: 1}


In [ ]:
labels.shape

In [ ]:
image.shape